CREATE TABLE TEST_TOBEDELETED (
 ID INT PRIMARY KEY auto_increment NOT NULL,
 TestMessage VARCHAR(250) NOT NULL
);

INSERT INTO TEST_TOBEDELETED VALUES (1, 'This is a TEST!');

UPDATE TEST_TOBEDELETED 
SET TestMessage = 'This is a TEST of Updating'
WHERE ID = 1;

SELECT * FROM TEST_TOBEDELETED;

DELETE FROM TEST_TOBEDELETED WHERE ID = 1;

DROP TABLE TEST_TOBEDELETED;


