CREATE DATABASE FToPayRespectsDB;

GRANT SELECT, CREATE, INSERT, UPDATE, ALTER, DELETE, DROP ON FToPayRespectsDB.* TO 'john'@'%' ;
GRANT SELECT, CREATE, INSERT, UPDATE, ALTER, DELETE, DROP ON FToPayRespectsDB.*  TO 'Matthew'@'%';
GRANT SELECT, CREATE, INSERT, UPDATE, ALTER, DELETE, DROP ON FToPayRespectsDB.* TO 'eman'@'%';
GRANT SELECT, CREATE, INSERT, UPDATE, ALTER, DELETE, DROP ON FToPayRespectsDB.* TO 'AleksandraL'@'%' ;
GRANT SELECT, CREATE, INSERT, UPDATE, ALTER, DELETE, DROP ON FToPayRespectsDB.* TO 'Felix'@'%';
